# Documentation: https://starship.rs/config

####################################################################################################
#                                              Prompt                                              #
####################################################################################################

format = '''
${username}${hostname}${directory}${python}([](fg:black bg:none)[${git_branch}${git_status}${git_state} ](bg:black)[](fg:black bg:none))
${character}
'''

add_newline = false

palette = 'aura'

[palettes.aura]
black = '#15141b'
blue = '#82e2ff'
gray = '#6d6d6d'
green = '#61ffca'
orange = '#ffca85'
pink = '#f694ff'
purple = '#a277ff'
red = '#ff6767'
white = '#edecee'

####################################################################################################
#                                             Modules                                              #
####################################################################################################

[character]
format = '${symbol} '

[directory]
format = '[](fg:black bg:none)[ ${path} ](green bg:black)[](fg:black bg:none)'
truncation_symbol = '…/'

[git_branch]
format = '[ ${branch}](pink bg:black)'

[git_state]
format = '[ ${state}( ${progress_current}/${progress_total})](white bg:black)'
am = 'apply-mailbox'
am_or_rebase = 'apply-mailbox / rebase'
bisect = 'bisect'
cherry_pick = 'cherry-pick'
merge = 'merge'
rebase = 'rebase'
revert = 'revert'

[git_status]
format = '( [${untracked}](#00ffff bg:black)[${modified}](#ffff00 bg:black)[${staged}](#00ff00 bg:black)[${deleted}](#ff0000 bg:black)[${renamed}](#ff00ff bg:black))[( ${ahead_behind})](#0000ff bg:black)'
ahead = '↑${count}'
behind = '↓${count}'
diverged = '↑${ahead_count} ↓${behind_count}'
modified = '○'
staged = '◉'
untracked = '∆'

[hostname]
format = '[](fg:black bg:none)[ ${hostname} ](blue bg:black)[](fg:black bg:none)'
ssh_only = false

[python]
format = '[](fg:black bg:none)[ ${virtualenv} ](orange bg:black)[](fg:black bg:none)'

[username]
format = '[ ${user} ](purple bg:black)[](fg:black bg:none)'
show_always = true
