# Documentation: `man 5 sway-output`

####################################################################################################
#                                       Output Configuration                                       #
####################################################################################################

# EVE Spectrum 4K
output "Advanced Micro Peripherals Ltd ES07D03 EVE213401080" {
    adaptive_sync on
    background ~/Pictures/wallpaper fill
    position 0 0
    resolution 3840x2160@144Hz
    scale 1.2
}

output "LG Electronics W2361 0x0000C245" {
    position 3200,450
    scale 1
}
